name: Publish Docker images

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:

  call-docker-build-gpt-code-ui:
    uses: localagi/ai-dedicated-workflows/.github/workflows/operation-docker-build-publish.yml@v2
    with:
      registry-repo-name: gpt-code-ui
      context-repository: ricklamers/gpt-code-ui
      context-repository-ref: ${{ github.ref_name }}
      registry-readme: README.docker.md
      tags: |
        type=schedule
        type=ref,event=branch
        type=semver,pattern={{version}}
      platforms: linux/amd64,linux/arm64/v8
    secrets: inherit
